-- 최댓값 구하기
SELECT MAX(DATETIME)
FROM ANIMAL_INS

-- 최솟값 구하기
SELECT MIN(DATETIME)
FROM ANIMAL_INS

-- 동물 수 구하기
SELECT COUNT(1)
FROM ANIMAL_INS

-- 중복 제거하기
/*
IS(NOT): NULL 비교 전용 연산자, NULL에 =를 쓰면 안먹힌다.
*/
SELECT COUNT(DISTINCT NAME) AS NAME_COUNT
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
